version: '3'
services:
  lne-channel:
    image: nouvelle0epoch/lne-channel
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
    ports:
      - 8082:8082
  database:
    image: mongo
    env_file:
      - ./environment
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data: {}